/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat_application;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author DEATHSTROKE
 */
public class LoginPage extends javax.swing.JFrame {
    int count=0;
        String get_user_id = null;
        String get_password = null;
        String first_name = null;
        String last_name = null;
        ResultSet r = null;
        PreparedStatement p = null;
        byte[] picture = null;
        ImageIcon ic = null;

   

        public void checkSaveData(){
        String getname, getpassword;
        File f = new File("userInfo.dat");
        if(f.exists()){
            try {
                Scanner get = new Scanner(f);
                getname = get.nextLine();
                getpassword = get.nextLine();
                new LoginPage(getname, getpassword).setVisible(true);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Chat_Application.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            new SignUpPage().setVisible(true);
        }
    }
    /**
     * Creates new form LoginPage
     */
    public LoginPage(String name, String password) {
        initComponents();
        juser_id.setText(name);
        juser_pass.setText(password);
    }
    public String phoneID()
    {
        return get_user_id;
    }
    public void saveInfo(){
        File f = new File("userInfo.dat");
        try {
            FileWriter save = new FileWriter("userInfo.dat");
            save.write(get_user_id+"\n"+get_password);
            save.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        juser_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        createAccountbtn = new javax.swing.JButton();
        Loginbtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        juser_pass = new javax.swing.JPasswordField();
        jshow = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phoenix-Login");
        setBackground(new java.awt.Color(255, 153, 0));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat_application/Images/icons8-username-48.png"))); // NOI18N
        jLabel2.setText("User ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 110, 168, 40);

        juser_id.setBackground(new java.awt.Color(102, 102, 255));
        juser_id.setFont(new java.awt.Font("Urdu Typesetting", 0, 14)); // NOI18N
        juser_id.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        juser_id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userIDcolor(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                afterColorUser(evt);
            }
        });
        juser_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juser_idActionPerformed(evt);
            }
        });
        jPanel1.add(juser_id);
        juser_id.setBounds(270, 120, 293, 25);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat_application/Images/icons8-login-rounded-48.png"))); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 180, 168, 50);

        createAccountbtn.setBackground(new java.awt.Color(0, 0, 255));
        createAccountbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        createAccountbtn.setForeground(new java.awt.Color(255, 255, 255));
        createAccountbtn.setText("Create Account");
        createAccountbtn.setBorder(null);
        createAccountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountbtnActionPerformed(evt);
            }
        });
        jPanel1.add(createAccountbtn);
        createAccountbtn.setBounds(90, 280, 160, 40);

        Loginbtn1.setBackground(new java.awt.Color(0, 0, 255));
        Loginbtn1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Loginbtn1.setForeground(new java.awt.Color(255, 255, 255));
        Loginbtn1.setText("Login");
        Loginbtn1.setBorder(null);
        Loginbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Loginbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(Loginbtn1);
        Loginbtn1.setBounds(470, 280, 90, 40);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log In");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 728, 42);

        btnClose.setBackground(new java.awt.Color(0, 0, 255));
        btnClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("X");
        btnClose.setBorder(null);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);
        btnClose.setBounds(711, 0, 70, 40);

        juser_pass.setBackground(new java.awt.Color(102, 102, 255));
        juser_pass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        juser_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                juser_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                juser_passFocusLost(evt);
            }
        });
        jPanel1.add(juser_pass);
        juser_pass.setBounds(270, 190, 293, 25);

        jshow.setBackground(new java.awt.Color(153, 153, 255));
        jshow.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jshow.setForeground(new java.awt.Color(255, 255, 255));
        jshow.setText("Show Password");
        jshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jshowActionPerformed(evt);
            }
        });
        jPanel1.add(jshow);
        jshow.setBounds(580, 190, 150, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat_application/Images/196-1963020_website-backgrounds-website-login-page-background.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 0, 780, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        setBounds(400, 200, 780, 380);
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountbtnActionPerformed
        //code for switching between login page and signup page
        dispose();
        new SignUpPage().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_createAccountbtnActionPerformed

    private void juser_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juser_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juser_idActionPerformed

    private void Loginbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Loginbtn1ActionPerformed
        //Goto Main Page
        
        DatabaseConnection dbc = new DatabaseConnection();
        Connection con = dbc.database();
        String query = "select PhoneNo, User_Password, FirstName, LastName, User_Image from UserInfo where PhoneNo=?";
        try {
            p = con.prepareStatement(query);
            p.setString(1, juser_id.getText());
            r = p.executeQuery();
            if(r.next())
            {
                get_user_id = r.getString("PhoneNo");
                first_name = r.getString("FirstName");
                last_name = r.getString("LastName");
                get_password = r.getString("User_Password");
                picture = r.getBytes("User_Image");
                ic = new ImageIcon(picture);
            }
            else{
                JOptionPane.showMessageDialog(null, "NO ACCOUNT EXISTS");
                return;
            }
            if(get_password.equals(new String(juser_pass.getPassword()))){
                dispose();
                saveInfo();
                new WelcomePage(first_name, last_name, ic, get_user_id).setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "INVALID PASSWORD. TRY AGAIN...");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
         
        // TODO add your handling code here:
    }//GEN-LAST:event_Loginbtn1ActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
            // TODO add your handling code here:
    }//GEN-LAST:event_btnCloseActionPerformed
    void setcolor(JTextField color_ctrl)
    {
        color_ctrl.setBackground(Color.blue);
    }
    void setAfterColor(JTextField color_ctrl)
    {
        color_ctrl.setBackground(Color.white);
    }
    private void userIDcolor(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userIDcolor
        setcolor(juser_id);
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDcolor

    private void afterColorUser(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_afterColorUser
        setAfterColor(juser_id);
        // TODO add your handling code here:
    }//GEN-LAST:event_afterColorUser

    private void juser_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_juser_passFocusGained
        setcolor(juser_pass);
        // TODO add your handling code here:
    }//GEN-LAST:event_juser_passFocusGained

    private void juser_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_juser_passFocusLost
        setAfterColor(juser_pass);
        // TODO add your handling code here:
    }//GEN-LAST:event_juser_passFocusLost

    private void jshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jshowActionPerformed
        if(jshow.isSelected())
        {
            juser_pass.setEchoChar((char)0);
            
        }
        else{
            juser_pass.setEchoChar('*');
         
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jshowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        LoginPage lp = new LoginPage(null, null);
        lp.checkSaveData();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbtn1;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton createAccountbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jshow;
    private javax.swing.JTextField juser_id;
    private javax.swing.JPasswordField juser_pass;
    // End of variables declaration//GEN-END:variables
}
