/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat_application;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.Socket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author DEATHSTROKE
 */
public class Messenger extends javax.swing.JFrame implements Runnable {
        String sent_msg;
        static String fname, lname, phno;
        ImageIcon img;
        static String phnum = null;
        String get_password = null;
        String first_name = null;
        String last_name = null;
        ResultSet r = null;
        PreparedStatement p = null;
        byte[] picture = null;
        BufferedWriter writer;
        BufferedReader reader;
        int totalmsg;
   
       

    /**
     * Creates new form Messenger
     */
     public String checkSaveData(){
        String getID = null, getpassword;
        File f = new File("userInfo.dat");
        if(f.exists()){
            try {
                Scanner get = new Scanner(f);
                getID = get.nextLine();
                getpassword = get.nextLine();
                new LoginPage(getID, getpassword).setVisible(true);
            } catch (FileNotFoundException ex) {
                //Exception Handling
            }
        }
        else{
            new SignUpPage().setVisible(true);
        }
        receiveDatabase(getID);
        return getID;
    }
     public void imageHandling()
     {
        ImageIcon icon = new ImageIcon(picture);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(juserpic.getWidth(), juserpic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimage = new ImageIcon(imgscale);
        juserpic.setIcon(scaledimage);
     }
    public Messenger() {
        initComponents();
        totalmsg = 0;
        phnum = getNum();
        String name = receiveDatabase(phnum);
        usertitle.setText(name);
        jnum.setText("Phone No: "+phnum);
        imageHandling();
        try{
            Socket s = new Socket("localhost", 1201);
            writer = new BufferedWriter(new OutputStreamWriter(s.getOutputStream()));
            reader = new BufferedReader(new InputStreamReader(s.getInputStream()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
        getMessages();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jnum = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        juserpic = new javax.swing.JLabel();
        usertitle = new javax.swing.JLabel();
        homebtn = new javax.swing.JButton();
        jreportbtn = new javax.swing.JButton();
        jtypearea = new javax.swing.JTextField();
        jsendbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtxtarea = new javax.swing.JScrollPane();
        jdisplaymsg = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phoenix-Messenger");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jnum.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jnum.setText("Contact No.");
        jPanel2.add(jnum);
        jnum.setBounds(150, 50, 290, 22);

        btnexit.setBackground(new java.awt.Color(0, 153, 153));
        btnexit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnexit.setText("Logout");
        btnexit.setBorder(null);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel2.add(btnexit);
        btnexit.setBounds(510, 10, 80, 30);
        jPanel2.add(juserpic);
        juserpic.setBounds(0, 0, 140, 110);

        usertitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usertitle.setText("User Name");
        jPanel2.add(usertitle);
        usertitle.setBounds(150, 20, 290, 22);

        homebtn.setBackground(new java.awt.Color(0, 153, 153));
        homebtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        homebtn.setText("Home");
        homebtn.setBorder(null);
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });
        jPanel2.add(homebtn);
        homebtn.setBounds(510, 70, 80, 30);

        jreportbtn.setBackground(new java.awt.Color(0, 153, 153));
        jreportbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jreportbtn.setText("Report");
        jreportbtn.setBorder(null);
        jreportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreportbtnActionPerformed(evt);
            }
        });
        jPanel2.add(jreportbtn);
        jreportbtn.setBounds(510, 40, 80, 30);

        jtypearea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jsendbtn.setBackground(new java.awt.Color(0, 153, 153));
        jsendbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jsendbtn.setText("Send");
        jsendbtn.setBorder(null);
        jsendbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsendbtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Type Message");

        jdisplaymsg.setEditable(false);
        jdisplaymsg.setBackground(new java.awt.Color(102, 102, 255));
        jdisplaymsg.setColumns(20);
        jdisplaymsg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jdisplaymsg.setForeground(new java.awt.Color(255, 255, 255));
        jdisplaymsg.setLineWrap(true);
        jdisplaymsg.setRows(5);
        jdisplaymsg.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtxtarea.setViewportView(jdisplaymsg);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chat Room");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtypearea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsendbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtxtarea, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtarea, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtypearea, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jsendbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(100, 70, 612, 579);
    }// </editor-fold>//GEN-END:initComponents

    private void jsendbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsendbtnActionPerformed
        //Code For Send Button
        DatabaseConnection db = new DatabaseConnection();
        Connection con = db.database();
        String Query = "insert into Text_Messages(UserID, TxtMessage)values(?,?)";
        String clientmsg = fname+" "+lname+": "+jtypearea.getText();
        jtypearea.setText("");
        try{
            writer.write(clientmsg+"\n");
            writer.flush();
            PreparedStatement p = con.prepareStatement(Query);
            p.setString(1, phnum);
            p.setString(2, clientmsg);
            p.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
    }//GEN-LAST:event_jsendbtnActionPerformed
public String receiveDatabase(String ph)
    {
        phnum = ph;
        DatabaseConnection dbc = new DatabaseConnection();
        Connection con = dbc.database();
        String query = "select PhoneNo, FirstName, LastName, Gender, User_Image from UserInfo where PhoneNo = ?";
        try {
            PreparedStatement p = con.prepareStatement(query);
            p.setString(1, phnum);
            ResultSet r = p.executeQuery();
            if(r.next())
            {
                phnum = r.getString("PhoneNo");
                fname = r.getString("FirstName");
                lname = r.getString("LastName");
                picture = r.getBytes("User_Image");
                img = new ImageIcon(picture);
            }
            else{
                new SignUpPage().setVisible(true);
                }
        } catch (SQLException ex) {
           
        }
        
        return fname+" "+lname;
        
    }
    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        dispose(); 
        new Chat_Application(img, fname +" "+ lname, phnum).setVisible(true);
    }//GEN-LAST:event_homebtnActionPerformed

    private void jreportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreportbtnActionPerformed
        //Report Button Handling
        DatabaseConnection db = new DatabaseConnection();
        Connection con = db.database();
        try{
            JasperDesign jdesign = JRXmlLoader.load("E:\\UNIVERSITY WORK\\Semesters\\Semester 04\\Courses\\Advanced Computer Programming\\Pheonix Mark V\\Chat_Application\\src\\chat_application\\ChatReport.jrxml");
            String query = "select * from Text_Messages";
            JRDesignQuery update = new JRDesignQuery();
            update.setText(query);
            jdesign.setQuery(update);
            JasperReport jreport = JasperCompileManager.compileReport(jdesign);
            JasperPrint jprint = JasperFillManager.fillReport(jreport, null, con);
            JasperViewer.viewReport(jprint);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error"+e);
        }
    }//GEN-LAST:event_jreportbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public void getMessages(){
        DatabaseConnection db = new DatabaseConnection();
        Connection con = db.database();
        try{
            String query = "select count(UserID) as TotalMsgs from Text_Messages";
            PreparedStatement p = con.prepareStatement(query);
            ResultSet r = p.executeQuery();
            if(r.next())
            {
                totalmsg = r.getInt("TotalMsgs");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No Record Found...");
            }
            
            for(int i = 1; i<=totalmsg; i++){
                query = "select TxtMessage from Text_Messages where ID = ?";
                p = con.prepareStatement(query);
                p.setInt(1, i);
                r = p.executeQuery();
                if(r.next()){
                    String msg = r.getString("TxtMessage");
                    jdisplaymsg.append(msg+"\n");
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "ERROR: "+e);
        }
    }
    
    public String getNum(){
        String getID = null, getpassword;
        File f = new File("userInfo.dat");
        if(f.exists()){
            try {
                Scanner get = new Scanner(f);
                getID = get.nextLine();
                getpassword = get.nextLine();
            } catch (FileNotFoundException ex) {
                //Exception Handling
            }
    }
        else{
            new SignUpPage().setVisible(true);
        }
        return getID;
    }
    
  public void run(){
        try{
            String msg = "";
            while((msg = reader.readLine()) != null){
                jdisplaymsg.append(msg + "\n");
            }
        }catch(Exception e){}
    }
    public static void main(String args[]) {
        Messenger m = new Messenger();
        m.checkSaveData();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Messenger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
       String serverreply = "";
       Thread th = new Thread(m);
       th.start();
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton homebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextArea jdisplaymsg;
    private static javax.swing.JLabel jnum;
    private javax.swing.JButton jreportbtn;
    private javax.swing.JButton jsendbtn;
    private javax.swing.JScrollPane jtxtarea;
    private javax.swing.JTextField jtypearea;
    private javax.swing.JLabel juserpic;
    private static javax.swing.JLabel usertitle;
    // End of variables declaration//GEN-END:variables
}
