/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat_application;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author DEATHSTROKE
 */
public class ResetPassword extends javax.swing.JFrame {
    String id, getpass;
    /**
     * Creates new form ResetPassword
     */
    public ResetPassword(String ph, String p) {
        initComponents();
        id = ph;
        getpass = p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        showpassword = new javax.swing.JCheckBox();
        confirmpass = new javax.swing.JPasswordField();
        oldpass = new javax.swing.JPasswordField();
        error = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        newpassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        newpass1 = new javax.swing.JLabel();
        newpass = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        closebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(775, 400));
        setResizable(false);

        jPanel1.setLayout(null);

        showpassword.setText("Show Password");
        showpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showpassword);
        showpassword.setBounds(580, 290, 150, 23);

        confirmpass.setBackground(new java.awt.Color(102, 102, 255));
        confirmpass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(confirmpass);
        confirmpass.setBounds(310, 280, 240, 30);

        oldpass.setBackground(new java.awt.Color(102, 102, 255));
        oldpass.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(oldpass);
        oldpass.setBounds(310, 160, 240, 30);

        error.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(error);
        error.setBounds(310, 120, 310, 30);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("NEXT");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 330, 100, 40);

        newpassword.setBackground(new java.awt.Color(102, 102, 255));
        newpassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(newpassword);
        newpassword.setBounds(310, 220, 240, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reset Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 690, 60);

        newpass1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        newpass1.setForeground(new java.awt.Color(255, 255, 255));
        newpass1.setText("Confirm Password");
        jPanel1.add(newpass1);
        newpass1.setBounds(110, 280, 160, 30);

        newpass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        newpass.setForeground(new java.awt.Color(255, 255, 255));
        newpass.setText("New Password");
        jPanel1.add(newpass);
        newpass.setBounds(110, 220, 130, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Old Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 160, 130, 30);

        closebtn.setBackground(new java.awt.Color(0, 102, 51));
        closebtn.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        closebtn.setForeground(new java.awt.Color(255, 255, 255));
        closebtn.setText("X");
        closebtn.setBorder(null);
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel1.add(closebtn);
        closebtn.setBounds(690, 0, 90, 50);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat_application/Images/196-1963020_website-backgrounds-website-login-page-background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 790, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        setBounds(100, 200, 775, 437);
    }// </editor-fold>//GEN-END:initComponents

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void showpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpasswordActionPerformed
        if(showpassword.isSelected())
        {
            oldpass.setEchoChar((char)0);
            newpassword.setEchoChar((char)0);
            confirmpass.setEchoChar((char)0);
        }
        else{
            oldpass.setEchoChar('*');
            newpassword.setEchoChar('*');
            confirmpass.setEchoChar('*');
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_showpasswordActionPerformed
    public String getNewPassword()
    {
        String pass = new String(newpassword.getPassword());
        return pass;
    }
    public String getConfirmPassword()
    {
        String pass = new String(confirmpass.getPassword());
        return pass;
    }
    public String getOldPassword()
    {
        String pass = new String(oldpass.getPassword());
        return pass;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(getOldPassword().equals(getpass)){
            if(getNewPassword().equals(getNewPassword())){
                DatabaseConnection db = new DatabaseConnection();
                Connection con = db.database();
                try{
            String query = "update UserInfo set User_Password = ? where PhoneNo = ?";
            PreparedStatement p = con.prepareStatement(query);
                p.setString(1, getConfirmPassword());
                p.setString(2, id);
                p.executeUpdate();
                error.setText("");
                JOptionPane.showMessageDialog(null, "Password Updated Successfully...");
                dispose();
        }catch(Exception e){
            //Exception Handling
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
            }
        }
        else{
            error.setText("Invalid Entries. Try Again...");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closebtn;
    private javax.swing.JPasswordField confirmpass;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newpass;
    private javax.swing.JLabel newpass1;
    private javax.swing.JPasswordField newpassword;
    private javax.swing.JPasswordField oldpass;
    private javax.swing.JCheckBox showpassword;
    // End of variables declaration//GEN-END:variables
}
