/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat_application;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author DEATHSTROKE
 */
public class SignUpPage extends javax.swing.JFrame {

    String f_password = null;
    String c_password = null;
    String s_gender=null;
    byte[] photo = null;
    String photo_location = null;
    ImageIcon img = null;
    /**
     * Creates new form SignUpPage
     */
    public String getID()
    {
        return phno.getText();
    }
    public String getFname(){
        return f_name.getText();
    }
    public String getLname(){
        return l_name.getText();
    }
    public String getGender(){
        if(male.isSelected())
        {
            s_gender = "Male";
            return s_gender;
        }
        else if(female.isSelected())
        {
            s_gender = "Female";
            return s_gender;
        }
        return null;
    }
    public SignUpPage() {
        initComponents();
        // Code For Radio Buttons   ***Gender***
        ButtonGroup bg = new ButtonGroup();
        bg.add(male);
        bg.add(female);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        f_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        l_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        jc_password = new javax.swing.JPasswordField();
        jshowpassword = new javax.swing.JCheckBox();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        juploadbox = new javax.swing.JLabel();
        jdatechoose = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phoenix-SignUp");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 130, 96, 20);

        f_name.setBackground(new java.awt.Color(102, 102, 255));
        f_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_nameActionPerformed(evt);
            }
        });
        jPanel1.add(f_name);
        f_name.setBounds(400, 130, 176, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(260, 170, 96, 17);

        l_name.setBackground(new java.awt.Color(102, 102, 255));
        l_name.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        l_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_nameActionPerformed(evt);
            }
        });
        jPanel1.add(l_name);
        l_name.setBounds(400, 170, 176, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Phone No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(260, 210, 96, 17);

        phno.setBackground(new java.awt.Color(102, 102, 255));
        phno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        phno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phnoActionPerformed(evt);
            }
        });
        jPanel1.add(phno);
        phno.setBounds(400, 210, 176, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 350, 96, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Confirm Password");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 380, 128, 30);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(470, 435, 110, 30);

        male.setBackground(new java.awt.Color(0, 153, 153));
        male.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        jPanel1.add(male);
        male.setBounds(410, 310, 55, 25);

        female.setBackground(new java.awt.Color(0, 153, 153));
        female.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        jPanel1.add(female);
        female.setBounds(490, 310, 71, 25);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Date of Birth");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(226, 260, 140, 30);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Already an Account");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(173, 435, 170, 30);

        jpassword.setBackground(new java.awt.Color(102, 102, 255));
        jpassword.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jpassword);
        jpassword.setBounds(410, 350, 176, 20);

        jc_password.setBackground(new java.awt.Color(102, 102, 255));
        jc_password.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jc_password);
        jc_password.setBounds(410, 390, 176, 20);

        jshowpassword.setBackground(new java.awt.Color(153, 153, 255));
        jshowpassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jshowpassword.setText("Show Password");
        jshowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jshowpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jshowpassword);
        jshowpassword.setBounds(620, 390, 170, 25);

        jDesktopPane1.setBackground(new java.awt.Color(153, 255, 255));
        jDesktopPane1.setMaximumSize(new java.awt.Dimension(200, 200));
        jDesktopPane1.setMinimumSize(new java.awt.Dimension(200, 200));

        juploadbox.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        juploadbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        juploadbox.setText("Upload Image");
        juploadbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                juploadboxMouseClicked(evt);
            }
        });

        jDesktopPane1.setLayer(juploadbox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(juploadbox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(juploadbox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.add(jDesktopPane1);
        jDesktopPane1.setBounds(20, 80, 190, 180);

        jdatechoose.setBackground(new java.awt.Color(204, 255, 255));
        jdatechoose.setDateFormatString("yyyy-MM-d ");
        jPanel1.add(jdatechoose);
        jdatechoose.setBounds(400, 260, 170, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(260, 310, 96, 30);

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Create Account");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 10, 728, 42);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat_application/Images/196-1963020_website-backgrounds-website-login-page-background.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setBounds(80, 80, 800, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void l_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_nameActionPerformed

    private void phnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phnoActionPerformed
    public String getDate(){
        String date  = ((JTextField)jdatechoose.getDateEditor().getUiComponent()).getText();
        return date;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DatabaseConnection dc = new DatabaseConnection();
        Connection con = dc.database();
        f_password = new String(jpassword.getPassword());
        c_password = new String(jc_password.getPassword());
        if(f_password.equals(c_password))
        {
            try{
            String Query = "insert into UserInfo(PhoneNo, FirstName, LastName, Date_of_Birth, Gender, User_Password, User_Image)values(?,?,?,?,?,?,?)";
            PreparedStatement p = con.prepareStatement(Query);
                p.setString(1, getID());
                p.setString(2, getFname());
                p.setString(3, getLname());
                p.setString(4, getDate());
                p.setString(5, getGender());
                p.setString(6, c_password);
                p.setBytes(7, photo);
                img = new ImageIcon(photo);
                p.executeUpdate();
                JOptionPane.showMessageDialog(null, "Account Created Successfully...");
               saveData();
                new WelcomePage(getFname(), getLname(), img, getID()).setVisible(true);
                dispose();
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error: "+e);
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Password Did Not Match... Try Again");
            return;
        }
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void saveData(){
            File f = new File("userInfo.dat");
        try {
            FileWriter save = new FileWriter("userInfo.dat");
            save.write(getID()+"\n"+c_password);
            save.close();
        } catch (IOException ex) {
            Logger.getLogger(LoginPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // switch between singup page and login page
        dispose();
        new LoginPage(null, null).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jshowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jshowpasswordActionPerformed
        if(jshowpassword.isSelected())
        {
            jpassword.setEchoChar((char)0);
            jc_password.setEchoChar((char)0);
        }
        else{
            jpassword.setEchoChar('*');
            jc_password.setEchoChar('*');
        }
    }//GEN-LAST:event_jshowpasswordActionPerformed
    public void imageHandling(){
        JFileChooser choose = new JFileChooser();
        choose.showOpenDialog(null);
        File f = choose.getSelectedFile();
        juploadbox.setIcon(new ImageIcon(f.toString()));
        photo_location = f.getAbsolutePath();
        ImageIcon icon = new ImageIcon(photo_location);
        Image img = icon.getImage();
        Image imgscale = img.getScaledInstance(juploadbox.getWidth(), juploadbox.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledimage = new ImageIcon(imgscale);
        juploadbox.setIcon(scaledimage);
        //converting into bytes
        
        File image = new File(photo_location);
        try {
            FileInputStream fin = new FileInputStream(image);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte[] b = new byte[1024];
            for(int check; (check = fin.read(b))!=-1;){
                baos.write(b, 0, check);
            }
            photo = baos.toByteArray();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void juploadboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_juploadboxMouseClicked
        //Getting file from the location
        imageHandling();
    }//GEN-LAST:event_juploadboxMouseClicked

    private void f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField f_name;
    private javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jc_password;
    private com.toedter.calendar.JDateChooser jdatechoose;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JCheckBox jshowpassword;
    private javax.swing.JLabel juploadbox;
    private javax.swing.JTextField l_name;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField phno;
    // End of variables declaration//GEN-END:variables
}
