/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat_application;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DEATHSTROKE
 */
public class WelcomePage extends javax.swing.JFrame {
    String name1, name2;
    ImageIcon recievepic;
    String phone;
    /**
     * Creates new form WelcomePage
     */
    public WelcomePage(String fname, String lname, ImageIcon rp, String ph) {
        initComponents();
        name1 = fname;
        name2 = lname;
        jLabel2.setText("Welcome Mr. "+name1+" "+name2);
        recievepic = rp;
        phone = ph;
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtncontinue = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome To Phoenix");
        setUndecorated(true);

        jPanel1.setLayout(null);

        jbtncontinue.setBackground(new java.awt.Color(0, 51, 51));
        jbtncontinue.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtncontinue.setForeground(new java.awt.Color(255, 255, 255));
        jbtncontinue.setText("Continue");
        jbtncontinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncontinueActionPerformed(evt);
            }
        });
        jPanel1.add(jbtncontinue);
        jbtncontinue.setBounds(100, 150, 280, 30);

        jLabel2.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome To Phoenix Chat");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 50, 500, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chat_application/Images/giphy-downsized.gif"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 280);

        jButton1.setText("jButton1");
        jPanel1.add(jButton1);
        jButton1.setBounds(40, 190, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        );

        setBounds(400, 200, 499, 271);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtncontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncontinueActionPerformed
        dispose();
        new Messenger().setVisible(true);
        
    }//GEN-LAST:event_jbtncontinueActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtncontinue;
    // End of variables declaration//GEN-END:variables
}
